export function configure(config) {
  config.globalResources([
    './attributes/bs-button-group',
    './attributes/bs-button-toolbar',
    './attributes/bs-form-group',
    './attributes/bs-input-group'
  ]);
  config.globalResources([
    './elements/bs-button',
    './elements/bs-checkbox',
    './elements/bs-footer',
    './elements/bs-form',
    './elements/bs-header',
    './elements/bs-icon',
    './elements/bs-input',
    './elements/bs-input-group-addon',
    './elements/bs-input-group-button',
    './elements/bs-nav',
    './elements/bs-navbar',
    './elements/bs-radio',
    './elements/bs-select',
    './elements/bs-split-button',
    './elements/bs-submit',
    './elements/bs-textarea'
  ]);
}
